runtime: nodejs
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_dir: build
service: fmc-crm-front-end
env: flex
manual_scaling:
  instances: 2

